// categories.js - Master list of visa categories
// This list can be extended by the user through the interface
const VISA_CATEGORIES = [
  "Tourist Visa",
  "Business Visa",
  "Student Visa",
  "Work Visa",
  "Family Visa",
  "Transit Visa",
  "Medical Visa",
  "Diplomatic Visa",
  "Courtesy Visa",
  "Journalist Visa",
  "Pilgrimage Visa",
  "Investment Visa",
  "Retirement Visa",
  "Study Visa",
  "Research Visa",
  "Conference Visa",
  "Employment Visa",
  "Dependent Visa",
  "Spouse Visa",
  "Parent Visa",
  "Exchange Visitor Visa",
  "Internship Visa",
  "Training Visa",
  "Volunteer Visa",
  "Religious Worker Visa",
  "Artist/Performer Visa",
  "Athlete Visa",
  "Cultural Exchange Visa",
  "Teaching Visa",
  "Student Exchange Visa"
];