// documents.js - Master list of common visa documents
const DOCUMENTS_LIST = [
  "Passport Copy",
  "Passport Size Photographs",
  "Bank Statement",
  "Bank Certificate",
  "Income Tax Returns",
  "Salary Slips",
  "Employment Letter",
  "Business License",
  "Company Registration Certificate",
  "Invitation Letter",
  "Sponsorship Letter",
  "Accommodation Proof",
  "Hotel Booking Confirmation",
  "Flight Itinerary",
  "Travel Insurance",
  "Visa Application Form",
  "Cover Letter",
  "Police Clearance Certificate",
  "Birth Certificate",
  "Marriage Certificate",
  "Divorce Certificate",
  "Death Certificate",
  "Medical Certificate",
  "Medical Insurance",
  "Vaccination Certificate",
  "Academic Transcripts",
  "Educational Certificates",
  "Degree/Diploma",
  "Professional Certifications",
  "Language Proficiency Test Results",
  "Curriculum Vitae (CV)/Resume",
  "Employment Contract",
  "Letter of Intent",
  "Statement of Purpose",
  "Recommendation Letters",
  "Financial Support Documents",
  "Property Documents",
  "Business Plan",
  "Trade License",
  "Audited Financial Statements",
  "Bank Guarantee",
  "Letter of Credit",
  "Export/Import Documents",
  "Customs Clearance Documents",
  "Criminal Record Check",
  "Health Insurance",
  "Proof of Relationship",
  "Family Registration Certificate",
  "Power of Attorney",
  "Affidavit of Support",
  "No Objection Certificate (NOC)",
  "Undertaking Letter",
  "Security Clearance",
  "Previous Passport Copies",
  "Visa Copies (Previous)",
  "Entry/Exit Stamps Copies",
  "Residence Permit Copy",
  "Work Permit Copy",
  "Student ID Card",
  "University Admission Letter",
  "Course Enrollment Certificate",
  "Research Proposal",
  "Conference Registration",
  "Event Invitation",
  "Gala Dinner Invitation",
  "Booking Confirmation",
  "Rental Agreement",
  "Mortgage Documents",
  "Tax Clearance Certificate",
  "Social Security Statement",
  "Pension Statement",
  "Investment Portfolio",
  "Stock Holdings",
  "Business Partnership Deed",
  "Memorandum of Association",
  "Articles of Association",
  "Board Resolution",
  "Shareholder Agreement",
  "Trademark Registration",
  "Patent Certificate",
  "Good Standing Certificate",
  "Professional License",
  "Driving License Copy",
  "Insurance Policy Documents",
  "Claim Documents",
  "Court Documents",
  "Judgment/Order Copy",
  "Arbitration Agreement",
  "Mediation Agreement",
  "Contract Agreement",
  "Service Agreement",
  "Consultancy Agreement",
  "Apostille Certificate",
  "Legalized Documents",
  "Translated Documents",
  "Attested Copies",
  "Embassy Registration",
  "Consular Registration",
  "Police Report",
  "Accident Report",
  "Fire Safety Certificate",
  "Building Approval",
  "Environmental Clearance",
  "Visa Fee",
  "Service Charges"
];
